### ISSUE TITLE
Error thrown

### ISSUE THREAD

**Issue by sdcooke** [nodkz/react-relay-network-layer#7]
I've noticed a difference between this network layer and the default network layer. If there is a network error the render method of the Relay.Renderer is called with the error. In the default network layer nothing else is done, in this network layer the error is then thrown after the render function has been called so you can't silently handle it.

I can't work out exactly where it's being thrown from - is this something you're aware of?

**Comment by nodkz** [comment]
Please provide more information 
- screenshot or stack-trace
- request/response screenshot from network tab in browser
- and of course you config of relay-network-layer

**Comment by sdcooke** [comment]
Thanks for your reply. Unfortunately we're not using Relay in the browser yet - just React Native (which could be why this is an issue). This is the stack trace it is reporting:

<img width="384" alt="screen shot 2016-06-20 at 10 39 43" src="https://cloud.githubusercontent.com/assets/136235/16189651/58d48c18-36d3-11e6-9694-ad3dffb71cf4.png">

This is the setup I'm using to test:
```
        const middleware = [
            urlMiddleware({
                url: (): string => this.props.graphql_url
            }),
            (next: Function): any => ((req: any): any => {
                Object.assign(req.headers, this.props.headers);
                return next(req);
            })
        ];
        this.relayEnv.injectNetworkLayer(new RelayNetworkLayer(middleware, {disableBatchQuery: true}));
```

To get the error I'm just turning off my local graphql server to simulate the network being down. The `render` prop of the `Relay.Renderer` component receives the error as it should but the difference between relay-network-layer and the default network layer is that the error from relay-network-layer still causes the react native red error screen but the default network layer does not.

I've looked at the promise coming out of both the default network layer and this network layer and they look exactly the same to me.

If this isn't something you've seen before and there's nothing jumping to mind about why it might be happening I can continue to debug - I was hoping it was something you might have an idea about though!

**Comment by nodkz** [comment]
Thanks for your detailed information.
You may look to this fork https://github.com/bmcmahen/react-relay-network-layer/commit/1967a3de0e004bb5fe7680c67c233d1ca6861c18 and comments to this commit.

I do not have react-native env to debug this issue. But you may! I think problem in `whatwg-fetch` polyfill. Will be great if you try just remove this line. And confirm stays problem or nor. 

Please let me know about your investigations.

**Comment by sdcooke** [comment]
Removing that line didn't fix the problem but I have worked out that it only happens when using remote debugging (i.e. via Chrome). If I use the native javascript engine for the app the problem doesn't happen - so at least it's not an issue that will impact production. I'll close this issue but if you want me to try anything else I'm happy to help.

Thanks - and sorry if I wasted any of your time!

**Comment by nodkz** [comment]
@sdcooke please check new version 1.2.0

Watwg-fetch was removed. May be it produces error.

**Comment by sdcooke** [comment]
I still get the error, I'm afraid.

**Comment by roman01la** [comment]
I'm also having this issue with `react-relay-network-layer` when network request fails. Basically when I get server response with an error, this error propagates through all Promise rejections (fetch -> fetchWrapper -> ...) and eventually it throws.

**Comment by nodkz** [comment]
Gotcha! Bump new version in hour. @roman01la be ready to test it. Write additionally, when publish on npm.

**Comment by roman01la** [comment]
Thanks for quick response!

**Comment by nodkz** [comment]
1.3.0 published 

It was some tricky problem. I hope it was solved.

In `react-native`, if some network problems (eg. offline) `fetch` throw error not via promise, so to catch this error, I just do such trick: 
```js
new Promise((resolve, reject) =>
  fetch(...)
    .then(res => resolve(res))
    .catch(err => reject(err))
```   

I suppose that arrow function (provided to promise constructor) catch thrown error and call `reject` implicitly. Something similar realized in [fbjs/fetchWithRetries](https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/fetch/fetchWithRetries.js#L50)

@roman01la @sdcooke please try new version, and write about results with your apps.

**Comment by roman01la** [comment]
Still the same error :(
I'll dig into RN network code on a sample project and try to find out where's the problem.

**Comment by nodkz** [comment]
@roman01la 

Agrrrr. Work in the blind. I have not react-native environment.
Try 1.3.1, just bumped. Change context for function (arrow-functions has callee context).

**Comment by nodkz** [comment]
@roman01la 
I'm publish small help how to fix packages https://medium.com/@nodkz/how-to-fix-nodejs-packages-within-your-app-and-send-pull-request-with-your-changes-8b4dcb89492b#.ojhbk7wvf

I think it will be useful.

**Comment by sdcooke** [comment]
I'm still seeing the same problem in 1.3.1 I'm afraid

**Comment by nodkz** [comment]
Bumped new version 1.3.6. 
Please check, the error should be gone.
Thanks to @kosmikko for the fix.

**Comment by jamesone** [comment]
I'm seeing the graphql errors being thrown with the latest version of this package.

**Comment by ersinakinci** [comment]
Same here.
